extract = 'total_dyn_inst: (\d+)'
benchmarks = './test/*/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}"
]

[runs.dce]
pipeline = [
    "bril2json",
    "./6120 --dce -p",
    "brili -p {args}"
]

[runs.lvn]
pipeline = [
    "bril2json",
    "./6120 --lvn -p",
    "brili -p {args}"
]

[runs.all]
pipeline = [
    "bril2json",
    "./6120 --dce-lvn -p",
    "brili -p {args}"
]