extract = 'total_dyn_inst: (\d+)'
benchmarks = './test/tdce/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}"
]

[runs.dce]
pipeline = [
    "bril2json",
    "./brilc dce",
    "brili -p {args}"
]