extract = 'total_dyn_inst: (\d+)'
benchmarks = './test/lvn/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}"
]

[runs.lvn]
pipeline = [
    "bril2json",
    "./brilc lvn",
    "brili -p {args}"
]