extract = 'total_dyn_inst: (\d+)'
benchmarks = './test/*/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p"
]

[runs.lvndce]
pipeline = [
    "bril2json",
    "./brilc lvn-dce",
    "bril2txt",
    "bril2json",
    "brili -p"
]